global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kafka-connect-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-connect-jmx'
    static_configs:
      - targets: ['kafka-connect:9097']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kafka-connect'

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9093']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kafka'
